security:
    providers:
        in_memory:
            memory:
              users:
                  admin:
                      password: novaway
                      roles: 'ROLE_ADMIN'
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext